'use client';
import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../lib/supabase';
import { Award, BriefcaseBusiness, FileText, GraduationCap, Home, LayoutDashboard, LogOut, Menu, Plus, Search, Settings, Sparkles, Target, User, X } from 'lucide-react';

type Section='Dashboard'|'Resumes'|'Certifications'|'Applications'|'Skills'|'Documents'|'Career Goals'|'Settings';
type Cert={id:string;name:string;issuer:string;expires:string;status:string};
type App={id:string;company:string;role:string;status:string;date:string};
const nav:[Section,any][]=[['Dashboard',LayoutDashboard],['Resumes',FileText],['Certifications',Award],['Applications',BriefcaseBusiness],['Skills',Sparkles],['Documents',FileText],['Career Goals',Target],['Settings',Settings]];

export default function HomePage(){
 const [section,setSection]=useState<Section>('Dashboard'); const [menu,setMenu]=useState(false); const [authed,setAuthed]=useState(false); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [register,setRegister]=useState(false); const [busy,setBusy]=useState(false);
 const [certs,setCerts]=useState<Cert[]>([]); const [apps,setApps]=useState<App[]>([]); const [showAdd,setShowAdd]=useState<'cert'|'app'|null>(null); const [toast,setToast]=useState('');
 useEffect(()=>{const saved=localStorage.getItem('careerhub-demo'); if(saved){setAuthed(true);setName(saved)} const c=localStorage.getItem('careerhub-certs');const a=localStorage.getItem('careerhub-apps');if(c)setCerts(JSON.parse(c));if(a)setApps(JSON.parse(a));},[]);
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2600)};
 const auth=async()=>{setBusy(true);const sb=supabase(); if(sb){const r=register?await sb.auth.signUp({email,password,options:{data:{full_name:name}}}):await sb.auth.signInWithPassword({email,password}); if(r.error){notify(r.error.message);setBusy(false);return} setAuthed(true);setName(name||email.split('@')[0]);}else{localStorage.setItem('careerhub-demo',name||email.split('@')[0]);setAuthed(true)}setBusy(false)};
 const logout=async()=>{await supabase()?.auth.signOut();localStorage.removeItem('careerhub-demo');setAuthed(false)};
 const addCert=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const c={id:crypto.randomUUID(),name:String(f.get('name')),issuer:String(f.get('issuer')),expires:String(f.get('expires')),status:'Active'};const next=[c,...certs];setCerts(next);localStorage.setItem('careerhub-certs',JSON.stringify(next));setShowAdd(null);notify('Certification added');};
 const addApp=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const a={id:crypto.randomUUID(),company:String(f.get('company')),role:String(f.get('role')),status:String(f.get('status')),date:String(f.get('date'))};const next=[a,...apps];setApps(next);localStorage.setItem('careerhub-apps',JSON.stringify(next));setShowAdd(null);notify('Application added');};
 if(!authed)return <Auth register={register} setRegister={setRegister} email={email} setEmail={setEmail} password={password} setPassword={setPassword} name={name} setName={setName} busy={busy} auth={auth}/>;
 return <div className="min-h-screen"><aside className="sidebar fixed left-0 top-0 z-20 flex h-screen w-[250px] flex-col border-r border-[#e4e4e7] bg-white/75 px-5 py-7 backdrop-blur-2xl"><div className="mb-10 px-2"><div className="flex items-center gap-2 font-semibold text-xl"><span className="grid h-9 w-9 place-items-center rounded-[11px] bg-black text-white">C</span>CareerHub</div><div className="mt-1 pl-11 text-xs text-[#8a8a91]">Your career, organized.</div></div><nav className="space-y-1">{nav.map(([label,Icon])=><button key={label} onClick={()=>setSection(label)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition ${section===label?'bg-[#f0f0f2] text-black':'text-[#68686f] hover:bg-[#f5f5f7]'}`}><Icon size={18}/>{label}</button>)}</nav><div className="mt-auto"><button onClick={logout} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-[#68686f] hover:bg-[#f5f5f7]"><LogOut size={18}/>Sign out</button></div></aside>
 <main className="content ml-[250px] min-h-screen px-10 py-8"><header className="mb-8 flex items-center justify-between"><div><button className="mobile-only mr-3" onClick={()=>setMenu(!menu)}><Menu/></button><p className="mb-1 text-sm text-[#7b7b82]">{new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</p><h1 className="text-[34px] font-semibold tracking-[-.045em]">{section==='Dashboard'?<>Good afternoon, {name.split(' ')[0]} <span>👋</span></>:section}</h1></div><div className="flex items-center gap-2"><button className="btn btn-secondary desktop-only"><Search size={17}/></button><div className="grid h-10 w-10 place-items-center rounded-full bg-black text-sm font-semibold text-white">{name.slice(0,1).toUpperCase()}</div></div></header>{section==='Dashboard'?<Dashboard certs={certs} apps={apps} setSection={setSection} setShowAdd={setShowAdd}/>:<SectionView section={section} certs={certs} apps={apps} setShowAdd={setShowAdd} notify={notify}/>}</main>
 <div className="mobile-nav fixed bottom-0 left-0 right-0 z-30 justify-around border-t border-[#dddde2] bg-white/90 p-2 backdrop-blur-xl">{nav.slice(0,5).map(([label,Icon])=><button key={label} onClick={()=>setSection(label)} className="grid place-items-center px-3 py-1 text-[10px] text-[#666]"><Icon size={19}/>{label.split(' ')[0]}</button>)}</div>
 {showAdd&&<Modal title={showAdd==='cert'?'Add certification':'Add job application'} close={()=>setShowAdd(null)}>{showAdd==='cert'?<form onSubmit={addCert} className="space-y-4"><input className="field" name="name" placeholder="Certification name" required/><input className="field" name="issuer" placeholder="Issuing organization" required/><label className="text-sm text-[#666]">Expiration date<input className="field mt-1" type="date" name="expires" required/></label><button className="btn btn-primary w-full">Add certification</button></form>:<form onSubmit={addApp} className="space-y-4"><input className="field" name="company" placeholder="Company" required/><input className="field" name="role" placeholder="Position" required/><select className="field" name="status"><option>Applied</option><option>Interview</option><option>Offer</option><option>Rejected</option></select><input className="field" type="date" name="date" required/><button className="btn btn-primary w-full">Add application</button></form>}</Modal>}
 {toast&&<div className="fixed bottom-6 right-6 z-50 rounded-full bg-black px-5 py-3 text-sm font-medium text-white shadow-2xl">{toast}</div>}
 </div>
}
function Auth(p:any){return <main className="grid min-h-screen place-items-center px-5"><div className="w-full max-w-[430px] fade"><div className="mb-8 text-center"><div className="mx-auto mb-5 grid h-14 w-14 place-items-center rounded-[17px] bg-black text-xl font-semibold text-white">C</div><h1 className="text-4xl font-semibold tracking-[-.05em]">CareerHub</h1><p className="mt-2 text-[#77777e]">Your career, organized.</p></div><div className="card p-7"><h2 className="text-xl font-semibold">{p.register?'Create your account':'Welcome back'}</h2><p className="mt-1 mb-6 text-sm text-[#77777e]">{p.register?'Start building your career workspace.':'Sign in to continue to your workspace.'}</p><form onSubmit={(e)=>{e.preventDefault();p.auth()}} className="space-y-3">{p.register&&<input className="field" placeholder="Full name" value={p.name} onChange={(e:any)=>p.setName(e.target.value)} required/>}<input className="field" type="email" placeholder="Email address" value={p.email} onChange={(e:any)=>p.setEmail(e.target.value)} required/><input className="field" type="password" placeholder="Password" value={p.password} onChange={(e:any)=>p.setPassword(e.target.value)} minLength={6} required/><button className="btn btn-primary mt-2 w-full" disabled={p.busy}>{p.busy?'Please wait…':p.register?'Create account':'Sign in'}</button></form><button onClick={()=>p.setRegister(!p.register)} className="mt-5 w-full text-sm font-medium text-[#0071e3]">{p.register?'Already have an account? Sign in':'Create an account'}</button></div><p className="mt-5 text-center text-xs text-[#99999f]">No Google. No Apple. Just your account.</p></div></main>}
function Dashboard({certs,apps,setSection,setShowAdd}:any){const exp=certs.filter((c:Cert)=>c.expires&&new Date(c.expires)<new Date(Date.now()+1000*60*60*24*90)).length;return <div className="fade space-y-6"><div className="grid gap-4 md:grid-cols-3"><Stat title="Certifications" value={certs.length} icon={<Award/>}/><Stat title="Applications" value={apps.length} icon={<BriefcaseBusiness/>}/><Stat title="Career progress" value="74%" icon={<Target/>}/></div><div className="grid gap-5 lg:grid-cols-[1.4fr_.8fr]"><div className="card p-6"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Recent activity</h2><p className="mt-1 text-sm text-[#77777e]">Your career workspace at a glance.</p></div><Sparkles className="text-[#8b8b92]" size={21}/></div><div className="mt-6 space-y-4">{certs.slice(0,3).map((c:Cert)=><Activity key={c.id} icon={<Award/>} title={`Added ${c.name}`} sub={c.issuer}/>)}{apps.slice(0,2).map((a:App)=><Activity key={a.id} icon={<BriefcaseBusiness/>} title={`Added ${a.role}`} sub={a.company}/>)}{!certs.length&&!apps.length&&<Empty title="Your workspace is ready" text="Add a certification or job application to start building your career timeline."/>}</div></div><div className="card p-6"><h2 className="text-xl font-semibold">Quick actions</h2><div className="mt-5 grid gap-3"><button onClick={()=>setShowAdd('cert')} className="btn btn-secondary flex items-center justify-between">Add certification <Plus size={18}/></button><button onClick={()=>setShowAdd('app')} className="btn btn-secondary flex items-center justify-between">Track application <Plus size={18}/></button><button onClick={()=>setSection('Resumes')} className="btn btn-secondary flex items-center justify-between">Build a resume <FileText size={18}/></button><button onClick={()=>setSection('Documents')} className="btn btn-secondary flex items-center justify-between">Upload document <FileText size={18}/></button></div>{exp>0&&<div className="mt-6 rounded-2xl bg-[#fff4e5] p-4 text-sm"><b>{exp} certification{exp>1?'s':''}</b> need attention within 90 days.</div>}</div></div></div>}
function Stat({title,value,icon}:any){return <div className="card p-5"><div className="mb-6 flex items-center justify-between"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#f2f2f5]">{icon}</span><span className="text-xs text-[#88888f]">This workspace</span></div><div className="text-3xl font-semibold tracking-[-.04em]">{value}</div><div className="mt-1 text-sm text-[#77777e]">{title}</div></div>}
function Activity({icon,title,sub}:any){return <div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#f2f2f5]">{icon}</span><div><div className="text-sm font-medium">{title}</div><div className="text-xs text-[#8a8a91]">{sub}</div></div></div>}
function Empty({title,text}:any){return <div className="rounded-2xl bg-[#f7f7f9] p-8 text-center"><div className="font-medium">{title}</div><div className="mt-1 text-sm text-[#77777e]">{text}</div></div>}
function SectionView({section,certs,apps,setShowAdd,notify}:any){if(section==='Certifications')return <div className="fade"><Toolbar text="Keep every credential in one place." action="Add certification" onClick={()=>setShowAdd('cert')}/><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{certs.map((c:Cert)=><div className="card p-5" key={c.id}><Award className="mb-5"/><h3 className="font-semibold">{c.name}</h3><p className="text-sm text-[#77777e]">{c.issuer}</p><div className="mt-5 rounded-xl bg-[#f5f5f7] p-3 text-xs">Expires {c.expires||'Not set'}</div></div>)}{!certs.length&&<Empty title="No certifications yet" text="Add your first credential to start your certification portfolio."/>}</div></div>;
 if(section==='Applications')return <div className="fade"><Toolbar text="Track every opportunity from application to offer." action="Add application" onClick={()=>setShowAdd('app')}/><div className="space-y-3">{apps.map((a:App)=><div className="card flex flex-wrap items-center justify-between gap-4 p-5" key={a.id}><div><h3 className="font-semibold">{a.role}</h3><p className="text-sm text-[#77777e]">{a.company} · {a.date}</p></div><span className="rounded-full bg-[#f0f0f2] px-3 py-1.5 text-xs font-semibold">{a.status}</span></div>)}{!apps.length&&<Empty title="No applications yet" text="Track jobs, internships, interviews, and offers here."/>}</div></div>;
 const copy:any={Resumes:['Create polished resumes with live preview and multiple templates.','Create your first resume'],Skills:['Build a living skills profile connected to your certifications and goals.','Add a skill'],Documents:['Store resumes, certificates, cover letters, and career files in one organized space.','Upload document'],['Career Goals']:['Turn career plans into measurable milestones.','Create a goal'],Settings:['Manage your profile, preferences, security, and workspace.','Open settings']}[section]||['Everything you need for your career workspace.','Get started'];return <div className="fade"><div className="card mx-auto max-w-3xl p-8 md:p-12"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-[#f1f1f4]">{section==='Resumes'?<FileText/>:section==='Skills'?<Sparkles/>:section==='Documents'?<FileText/>:section==='Career Goals'?<Target/>:<Settings/>}</div><h2 className="mt-6 text-3xl font-semibold tracking-[-.04em]">{section}</h2><p className="mt-2 max-w-xl text-[#77777e]">{copy[0]}</p><button onClick={()=>notify(`${copy[1]} is ready to build next.`)} className="btn btn-primary mt-7">{copy[1]} <Plus className="ml-1 inline" size={17}/></button></div></div>}
function Toolbar({text,action,onClick}:any){return <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><p className="text-[#77777e]">{text}</p><button onClick={onClick} className="btn btn-primary"><Plus className="mr-1 inline" size={17}/>{action}</button></div>}
function Modal({title,close,children}:any){return <div className="fixed inset-0 z-40 grid place-items-center bg-black/25 p-5 backdrop-blur-sm"><div className="card w-full max-w-md p-6"><div className="mb-6 flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><button onClick={close}><X size={20}/></button></div>{children}</div></div>}
